# templates/ingress.yaml (Add TLS section)
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80
{{- end }}
