appName: myhelmapp

port: 80

namespace: test

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: devopsjourney1/mywebapp
  tag: latest
ingress:
  enabled: true
  className: "nginx" # Or your ingressClassName
  host: "teo.com" # Replace with your domain
  tls:
    enabled: true
    secretName: teo-tls-dev
