appName: myapp

port: 80

namespace: teonew

nginx:
  image:
    repository: nginx
    tag: latest
    pullPolicy: Always
  deployment:
    replicas: 2
    containerPort: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'
    
ingress:
  enabled: true
  className: "nginx" # Or your ingressClassName
  host: "teo.com" # Replace with your domain
  tls:
    enabled: true
    secretName: teo-tls-de
